### ISSUE TITLE
13 card has 14 dots

### ISSUE THREAD

**Issue by ArjendeMooij-Tritac** [Carduelis/poker-widget-preact#1]
During on of our planning poker sessions I noticed that the cards 1 through 20 have an amount of dots corresponding to their value. Except for the 13, it has 14 dots. This might be some cruel anti-OCD joke, but also possibly an honest mistake. Can you change it to 13 dots.
![13](https://user-images.githubusercontent.com/62546827/100553589-f3aedc00-328e-11eb-96de-41f04ba0730e.png)

**Comment by Carduelis** [comment]
@ArjendeMooij-Tritac @koen-dev  Thanks for collaboration!

**Comment by Carduelis** [comment]
Going to deploy this week
