### ISSUE TITLE
Images are cut on current version of Miro

### ISSUE THREAD

**Issue by tprochazka** [Carduelis/poker-widget-preact#3]
It does not reveal quite often and if it reveals it is cut, check this screenshot: 

![image](https://user-images.githubusercontent.com/172094/109983102-ceed5900-7d02-11eb-8e29-f54f57fe128c.png)

And it also blinking.

**Comment by Carduelis** [comment]
@tprochazka Thank you for your feedback!
We figured the bug out! It will take some routine work, and we will deploy the new version soon!

**Comment by Carduelis** [comment]
@tprochazka, please, check the new released version!
We fixed trimmed cards and also reworked the way of the installation process.

**Comment by tprochazka** [comment]
I just tested it, the crop is gone, revealing looks more reliable, it just still somehow blinking and sometimes happen that some card not reveal, but pressing the button more times usually helps. So it now definitely much better. Thanks!

**Comment by tprochazka** [comment]
And when somebody reveals cards. The left panel remains the same for all others participants. It looks like a new issue.

**Comment by Carduelis** [comment]
@tprochazka Thank you for your feedback. I'll take a look onto this.
