### ISSUE TITLE
Poker card images being removed after reveal

### ISSUE THREAD

**Issue by Friandia** [Carduelis/poker-widget-preact#4]
since latest miro update the poker card images are removed instead of revealed after pressing the reveal button.

![2022-02-Miro-PlanningPoker](https://user-images.githubusercontent.com/49301710/152122926-fe53df51-64ca-47e0-9015-226f766e710e.png)

Reinstall of the app did not solve, multiple users and teams are affected

**Comment by Carduelis** [comment]
@Friandia Thank you very much for the issue. Sorry for the late response.
The problem has been solved with another Miro update.
By the way, we are testing a new version of the Planning Poker App with the Miro team. We hope to release it in a few days.
